export const ComandoConstants = {
    SEGUIR_PROXIMA_PERGUNTA: 'SEGUIR_PROXIMA_PERGUNTA',
    LOOP_FILHOS: 'LOOP_FILHOS',
    CONCATENAR_MEMBRO_INICIO: 'CONCATENAR_MEMBRO_INICIO',
    CONCATENAR_MEMBRO_FINAL: 'CONCATENAR_MEMBRO_FINAL',
    ENCERRAR_FLUXO: 'ENCERRAR_FLUXO',
    CONCATENAR_FAMILIA: 'CONCATENAR_FAMILIA'
}